### ISSUE TITLE
Can you add this with EURO too ?

### ISSUE THREAD

**Issue by ghost** [nicksergeant/suchvalue#3]

**Comment by nicksergeant** [comment]
@ghost I would like to, but none of the public APIs support it. https://api.cryptonator.com/api/ticker/doge-usd supports it but they use JS to redirect to the actual data (so it will only work in a browser [unless I implement phantomjs or other headless browser, which I am not going to do]). They are attempting to block programmatic access, it seems.

If there is a public API for converting Dogecoin to other currencies, I would be happy to support it.
